SELECT L.IDLISTA,NOMBRE,DESCRIPCION,PRIVILEGIOS,IMGBINARY,IMGTYPE FROM LISTA AS L 
INNER JOIN GRUPOS AS G ON G.IDLISTA = L.IDLISTA 
WHERE G.IDUSUARIO = 1 AND (L.NOMBRE LIKE '%Descripcion%' OR L.DESCRIPCION LIKE '%Descripcion%') ORDER BY L.NOMBRE ASC;