/* Restauracion de la tabla LOG*/
INSERT INTO adrianpedro2122.HISTORICO (NOMBRE, CANTIDAD) VALUES ('Número de Listas Creadas:', 0);
INSERT INTO adrianpedro2122.HISTORICO (NOMBRE, CANTIDAD) VALUES ('Número de Listas Activas:', 0);
INSERT INTO adrianpedro2122.HISTORICO (NOMBRE, CANTIDAD) VALUES ('Número de Listas con Elementos pendientes de compra:', 0);

/* Insercion de usuarios */
INSERT INTO adrianpedro2122.USUARIOS (DNI, NOMBRE, APELLIDOS, TELEFONO, EMAIL, PASSWORD, FNAC, SEXO, ROL, ESTADO, IMGTYPE, IMGBINARY, LASTLOGIN) VALUES  ('50505050A', 'Admin', 'Admin', '+34 678345645', 'admin@void.ugr.es', '1234', '1977/01/01', 'Masculino', 'Administrador', 'Activo', 'image/png', LOAD_FILE('../assets/usuarios/usuarios.jpg'), NOW());
INSERT INTO adrianpedro2122.USUARIOS (DNI, NOMBRE, APELLIDOS, TELEFONO, EMAIL, PASSWORD, FNAC, SEXO, ROL, ESTADO, IMGTYPE, IMGBINARY, LASTLOGIN) VALUES  ('51505050A', 'Juan', 'Martin', '+34 678345245', 'juan@void.ugr.es', '1234', '1977/01/01', 'Masculino', 'Administrador', 'Activo', 'image/png', LOAD_FILE('/var/upload/usuarios/juan.png'), NOW());
INSERT INTO adrianpedro2122.USUARIOS (DNI, NOMBRE, APELLIDOS, TELEFONO, EMAIL, PASSWORD, FNAC, SEXO, ROL, ESTADO, IMGTYPE, IMGBINARY, LASTLOGIN) VALUES  ('51505850A', 'Maria', 'Jimenez', '+34 618345746', 'maria@void.ugr.es', '1234', '1977/01/01', 'Femenino', 'Usuario', 'Inactivo', 'image/png', LOAD_FILE('/var/upload/usuarios/maria.png'), NOW());
INSERT INTO adrianpedro2122.USUARIOS (DNI, NOMBRE, APELLIDOS, TELEFONO, EMAIL, PASSWORD, FNAC, SEXO, ROL, ESTADO, IMGTYPE, IMGBINARY, LASTLOGIN) VALUES  ('50525050A', 'Ana', 'Fernandez', '+34 678323045', 'ana@void.ugr.es', '1234', '1977/01/01', 'Femenino', 'Usuario', 'Activo', 'image/png', LOAD_FILE('/var/upload/usuarios/ana.png'), NOW());
INSERT INTO adrianpedro2122.USUARIOS (DNI, NOMBRE, APELLIDOS, TELEFONO, EMAIL, PASSWORD, FNAC, SEXO, ROL, ESTADO, IMGTYPE, IMGBINARY, LASTLOGIN) VALUES  ('51505150A', 'Pepe', 'Perez', '+34 678305945', 'pepe@void.ugr.es', '1234', '1977/01/01', 'Masculino', 'Usuario', 'Activo', 'image/png', LOAD_FILE('/var/upload/usuarios/pepe.png'), NOW());


/*REGISTRO DE  LISTAS*/
INSERT INTO adrianpedro2122.LISTA(IDPROPIETARIO,NOMBRE,DESCRIPCION,FECHA,IMGTYPE,IMGBINARY) VALUES (2, "Lista1","Mi lista personal","2022-01-05 12:49:29","image/png",LOAD_FILE("/var/upload/listas/listas.png"));
INSERT INTO adrianpedro2122.LISTA(IDPROPIETARIO,NOMBRE,DESCRIPCION,FECHA,IMGTYPE,IMGBINARY) VALUES (3, "Lista2","Lista de la compra","2022-02-05 17:49:29","image/png",LOAD_FILE("/var/upload/listas/listas.png"));
INSERT INTO adrianpedro2122.LISTA(IDPROPIETARIO,NOMBRE,DESCRIPCION,FECHA,IMGTYPE,IMGBINARY) VALUES (3, "Lista3","Lista de cosas que faltan en casa","2021-03-05 17:49:29","image/png",LOAD_FILE("/home/var/upload/listas/listas.png"));
INSERT INTO adrianpedro2122.LISTA(IDPROPIETARIO,NOMBRE,DESCRIPCION,FECHA,IMGTYPE,IMGBINARY) VALUES (3, "Lista4","Lista para los que vayan a comprar","2022-04-05 12:49:29","image/png",LOAD_FILE("/var/upload/listas/listas.png"));
INSERT INTO adrianpedro2122.LISTA(IDPROPIETARIO,NOMBRE,DESCRIPCION,FECHA,IMGTYPE,IMGBINARY) VALUES (3, "Lista5","Lista del mercadona","2021-06-05 17:49:29","image/png",LOAD_FILE("/var/upload/listas/listas.png"));
INSERT INTO adrianpedro2122.LISTA(IDPROPIETARIO,NOMBRE,DESCRIPCION,FECHA,IMGTYPE,IMGBINARY) VALUES (3, "Lista6","Lista para recordar cosas que comprar",NOW(),"image/png",LOAD_FILE("/home/var/upload/listas/listas.png"));
INSERT INTO adrianpedro2122.LISTA(IDPROPIETARIO,NOMBRE,DESCRIPCION,FECHA,IMGTYPE,IMGBINARY) VALUES (5, "Lista7","Lista de cosas varias","2022-06-05 12:49:29","image/png",LOAD_FILE("/var/upload/listas/listas.png"));


/* REGISTRO DE PRODUCTOS */
INSERT INTO adrianpedro2122.PRODUCTOS(NOMBRE) VALUES ("Agua");
INSERT INTO adrianpedro2122.PRODUCTOS(NOMBRE) VALUES ("Leche");
INSERT INTO adrianpedro2122.PRODUCTOS(NOMBRE) VALUES ("Pan de molde");
INSERT INTO adrianpedro2122.PRODUCTOS(NOMBRE) VALUES ("Colacao grande");
INSERT INTO adrianpedro2122.PRODUCTOS(NOMBRE) VALUES ("Cereales chocapic");
INSERT INTO adrianpedro2122.PRODUCTOS(NOMBRE) VALUES ("Bollicao");
INSERT INTO adrianpedro2122.PRODUCTOS(NOMBRE) VALUES ("Galletas maría");
INSERT INTO adrianpedro2122.PRODUCTOS(NOMBRE) VALUES ("Gel de ducha");
INSERT INTO adrianpedro2122.PRODUCTOS(NOMBRE) VALUES ("Huevos");
INSERT INTO adrianpedro2122.PRODUCTOS(NOMBRE) VALUES ("Café");
INSERT INTO adrianpedro2122.PRODUCTOS(NOMBRE) VALUES ("Platanos");
INSERT INTO adrianpedro2122.PRODUCTOS(NOMBRE) VALUES ("Manzanas");
INSERT INTO adrianpedro2122.PRODUCTOS(NOMBRE) VALUES ("Kiwis");
INSERT INTO adrianpedro2122.PRODUCTOS(NOMBRE) VALUES ("Jabón de manos");
INSERT INTO adrianpedro2122.PRODUCTOS(NOMBRE) VALUES ("Clínex");
INSERT INTO adrianpedro2122.PRODUCTOS(NOMBRE) VALUES ("Suavizante");
INSERT INTO adrianpedro2122.PRODUCTOS(NOMBRE) VALUES ("Detergente");

/* REGISTRO DE PRODUCTOS AÑADIDOS A UNA LISTA*/
/* Lista 1 */
INSERT INTO adrianpedro2122.LISTAPRODUCTOS VALUES(1,3,2);
INSERT INTO adrianpedro2122.LISTAPRODUCTOS VALUES(1,8,1);
INSERT INTO adrianpedro2122.LISTAPRODUCTOS VALUES(1,15,3);
/* Lista 2 */
INSERT INTO adrianpedro2122.LISTAPRODUCTOS VALUES(2,1,2);
INSERT INTO adrianpedro2122.LISTAPRODUCTOS VALUES(2,5,1);
INSERT INTO adrianpedro2122.LISTAPRODUCTOS VALUES(2,15,5);
INSERT INTO adrianpedro2122.LISTAPRODUCTOS VALUES(2,11,2);
INSERT INTO adrianpedro2122.LISTAPRODUCTOS VALUES(2,8,2);
INSERT INTO adrianpedro2122.LISTAPRODUCTOS VALUES(2,3,1);
INSERT INTO adrianpedro2122.LISTAPRODUCTOS VALUES(2,4,3);
/* Lista 3 */
INSERT INTO adrianpedro2122.LISTAPRODUCTOS VALUES(3,6,2);
INSERT INTO adrianpedro2122.LISTAPRODUCTOS VALUES(3,9,1);
INSERT INTO adrianpedro2122.LISTAPRODUCTOS VALUES(3,12,3);
INSERT INTO adrianpedro2122.LISTAPRODUCTOS VALUES(3,7,2);
INSERT INTO adrianpedro2122.LISTAPRODUCTOS VALUES(3,14,1);
/* Lista 4 */
INSERT INTO adrianpedro2122.LISTAPRODUCTOS VALUES(4,16,1);
INSERT INTO adrianpedro2122.LISTAPRODUCTOS VALUES(4,17,1);
/* Lista 5 */
INSERT INTO adrianpedro2122.LISTAPRODUCTOS VALUES(5,11,10);
INSERT INTO adrianpedro2122.LISTAPRODUCTOS VALUES(5,12,5);
INSERT INTO adrianpedro2122.LISTAPRODUCTOS VALUES(5,13,8);
/* Lista 6 */
INSERT INTO adrianpedro2122.LISTAPRODUCTOS VALUES(6,5,1);
INSERT INTO adrianpedro2122.LISTAPRODUCTOS VALUES(6,2,2);
INSERT INTO adrianpedro2122.LISTAPRODUCTOS VALUES(6,17,4);
INSERT INTO adrianpedro2122.LISTAPRODUCTOS VALUES(6,13,2);
/* Lista 7 */
INSERT INTO adrianpedro2122.LISTAPRODUCTOS VALUES(7,14,1);
INSERT INTO adrianpedro2122.LISTAPRODUCTOS VALUES(7,12,5);
INSERT INTO adrianpedro2122.LISTAPRODUCTOS VALUES(7,8,1);

/* Asociacion de USUARIOS y LISTA*/
/* Los Editores solo tienen permiso para aniadir mas productos a las listas*/
INSERT INTO adrianpedro2122.GRUPOS VALUES (1,2,'Propietario');
INSERT INTO adrianpedro2122.GRUPOS VALUES (2,3,'Propietario');
INSERT INTO adrianpedro2122.GRUPOS VALUES (3,3,'Propietario');
INSERT INTO adrianpedro2122.GRUPOS VALUES (4,3,'Propietario');
INSERT INTO adrianpedro2122.GRUPOS VALUES (5,3,'Propietario');
INSERT INTO adrianpedro2122.GRUPOS VALUES (6,3,'Propietario');
INSERT INTO adrianpedro2122.GRUPOS VALUES (7,5,'Propietario');

INSERT INTO adrianpedro2122.GRUPOS VALUES (1,4,'Editor');
INSERT INTO adrianpedro2122.GRUPOS VALUES (3,2,'Editor');

INSERT INTO adrianpedro2122.GRUPOS VALUES (1,3,'Lector');
INSERT INTO adrianpedro2122.GRUPOS VALUES (2,2,'Lector');
INSERT INTO adrianpedro2122.GRUPOS VALUES (3,4,'Lector');

/* Historico de produtos inicial */
INSERT INTO adrianpedro2122.HISTORICOPRODUCTOS (NOMBRE,CANTIDAD) VALUES ("Coliflor", 14);
INSERT INTO adrianpedro2122.HISTORICOPRODUCTOS (NOMBRE,CANTIDAD) VALUES ("Naranja", 12);
INSERT INTO adrianpedro2122.HISTORICOPRODUCTOS (NOMBRE,CANTIDAD) VALUES ("Limón", 20);
INSERT INTO adrianpedro2122.HISTORICOPRODUCTOS (NOMBRE,CANTIDAD) VALUES ("Piña", 6);
INSERT INTO adrianpedro2122.HISTORICOPRODUCTOS (NOMBRE,CANTIDAD) VALUES ("Zanahoria", 15);
INSERT INTO adrianpedro2122.HISTORICOPRODUCTOS (NOMBRE,CANTIDAD) VALUES ("Pollo", 7);
INSERT INTO adrianpedro2122.HISTORICOPRODUCTOS (NOMBRE,CANTIDAD) VALUES ("Queso", 33);
INSERT INTO adrianpedro2122.HISTORICOPRODUCTOS (NOMBRE,CANTIDAD) VALUES ("Miel", 15);
INSERT INTO adrianpedro2122.HISTORICOPRODUCTOS (NOMBRE,CANTIDAD) VALUES ("Chocolate", 17);
INSERT INTO adrianpedro2122.HISTORICOPRODUCTOS (NOMBRE,CANTIDAD) VALUES ("Pasta", 20);

