/*REGISTRO DE  LISTAS*/

INSERT INTO LISTACOMPRA.LISTA(NOMBRE,DESCRIPCION,FECHA,IMGTYPE,IMGBINARY) VALUES ("Lista1","Descripcion",NOW(),"image/png",LOAD_FILE("/var/www/html/segmentar-listas.png"));
INSERT INTO LISTACOMPRA.LISTA(NOMBRE,DESCRIPCION,FECHA,IMGTYPE,IMGBINARY) VALUES ("Lista2","Descripcion",NOW(),"image/jpg",LOAD_FILE("/var/www/html/lista-seo.jpg"));

/* REGISTRO DE PRODUCTOS */
INSERT INTO LISTACOMPRA.PRODUCTOS(NOMBRE, DESCRIPCION, IMGTYPE, IMGBINARY) VALUES ("Fanta", "La fanta", "image/png", LOAD_FILE("/var/www/html/220px-Fanta_logo_(2018).png"));
INSERT INTO LISTACOMPRA.PRODUCTOS(NOMBRE, DESCRIPCION, IMGTYPE, IMGBINARY) VALUES ("Cocacola", "La cocacola", "image/png", LOAD_FILE("/var/www/html/200px-Coca-Cola_logo.svg.png "));

/* REGISTRO DE PRODUCTOS AÑADIDOS A UNA LISTA*/
INSERT INTO LISTACOMPRA.LISTAPRODUCTOS VALUES(1,1,10);
INSERT INTO LISTACOMPRA.LISTAPRODUCTOS VALUES(2,1,20);
INSERT INTO LISTACOMPRA.LISTAPRODUCTOS VALUES(1,2,100);

/* Insercion de usuarios */
INSERT INTO LISTACOMPRA.USUARIOS (DNI, NOMBRE, APELLIDOS, TELEFONO, EMAIL, PASSWORD, FNAC, SEXO, ROL, ESTADO, IMGTYPE, IMGBINARY, LASTLOGIN) VALUES  ('50505050A', 'Prueba', 'Apellidos', '+34 678345645', 'email@pruebas.com', 'password', '1977/01/01', 'Masculino', 'Administrador', 'Activo', 'image/jpg', LOAD_FILE('/var/www/html/robot-2000.jpg'), NOW());
INSERT INTO LISTACOMPRA.USUARIOS (DNI, NOMBRE, APELLIDOS, TELEFONO, EMAIL, PASSWORD, FNAC, SEXO, ROL, ESTADO, IMGTYPE, IMGBINARY, LASTLOGIN) VALUES  ('51505050A', 'Prueba2', 'Apellidos', '+34 178345645', 'email2@pruebas.com', 'password', '1977/01/01', 'Masculino', 'Usuario', 'Activo', 'image/jpg', LOAD_FILE('/var/www/html/robot-2000.jpg'), NOW());

/* Asociacion de USUARIOS y LISTA*/
/* Los Editores solo tienen permiso para aniadir mas productos a las listas*/
INSERT INTO LISTACOMPRA.GRUPOS VALUES (1,1,'Editor');
INSERT INTO LISTACOMPRA.GRUPOS VALUES (1,2,'Lector');

INSERT INTO LISTACOMPRA.GRUPOS VALUES (2,1,'Lector');
INSERT INTO LISTACOMPRA.GRUPOS VALUES (2,2,'Editor');
