DROP DATABASE IF EXISTS LISTACOMPRA;
CREATE DATABASE LISTACOMPRA;

DROP USER IF EXISTS 'adminlistacompra'@'localhost';
CREATE USER 'adminlistacompra'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON LISTACOMPRA.* TO 'adminlistacompra'@'localhost';
FLUSH PRIVILEGES;

DROP TABLE IF EXISTS LISTACOMPRA.USUARIOS;
CREATE TABLE LISTACOMPRA.USUARIOS (
  IDUSUARIO INT NOT NULL AUTO_INCREMENT,
  DNI VARCHAR(9) UNIQUE,
  NOMBRE VARCHAR(50),
  APELLIDOS VARCHAR(100),
  TELEFONO VARCHAR(20) UNIQUE,
  EMAIL VARCHAR(200) UNIQUE,
  PASSWORD VARCHAR(45),
  FNAC DATE,
  SEXO ENUM('Masculino','Femenino'),
  ROL ENUM('Administrador','Usuario'),
  ESTADO ENUM('Activo','Inactivo'),
  IMGTYPE ENUM('image/jpeg', 'image/png', 'image/jpg'),
  IMGBINARY LONGBLOB,
  LASTLOGIN DATETIME,

  CONSTRAINT PK_IDUSUARIO PRIMARY KEY(IDUSUARIO)
);

DROP TABLE IF EXISTS LISTACOMPRA.LISTA;
CREATE TABLE LISTACOMPRA.LISTA (
  IDLISTA INT NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR (45),
  DESCRIPCION VARCHAR(45),
  FECHA DATETIME,
  IMGTYPE ENUM('image/jpeg', 'image/png', 'image/jpg'),
  IMGBINARY LONGBLOB,

  CONSTRAINT PK_IDLISTA PRIMARY KEY(IDLISTA)
);

DROP TABLE IF EXISTS LISTACOMPRA.PRODUCTOS;
CREATE TABLE LISTACOMPRA.PRODUCTOS (
  IDPRODUCTO INT NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(45),
  DESCRIPCION VARCHAR(45),

  CONSTRAINT PK_IDPRODUCTO PRIMARY KEY(IDPRODUCTO)
);


DROP TABLE IF EXISTS LISTACOMPRA.LISTAPRODUCTOS;
CREATE TABLE LISTACOMPRA.LISTAPRODUCTOS (
  IDLISTA INT,
  IDPRODUCTO INT,
  CANTIDAD INT,

  CONSTRAINT FK_LISTACOMPRA_LISTAID FOREIGN KEY(IDLISTA) REFERENCES LISTA(IDLISTA),
  CONSTRAINT FK_LISTACOMPRA_IDPRODUCTO FOREIGN KEY(IDPRODUCTO) REFERENCES PRODUCTOS(IDPRODUCTO)
);

DROP TABLE IF EXISTS LISTACOMPRA.GRUPOS;
CREATE TABLE LISTACOMPRA.GRUPOS (
  IDLISTA INT,
  IDUSUARIO INT,
  PRIVILEGIOS ENUM('Propietario','Editor','Lector'),

  CONSTRAINT FK_GRUPOS_LISTAID FOREIGN KEY(IDLISTA) REFERENCES LISTA(IDLISTA),
  CONSTRAINT FK_GRUPOS_IDUSUARIO FOREIGN KEY(IDUSUARIO) REFERENCES USUARIOS(IDUSUARIO)
);


/*Tablas de log*/
DROP TABLE IF EXISTS LISTACOMPRA.LOG;
CREATE TABLE LISTACOMPRA.LOG(
  IDLOG INT NOT NULL AUTO_INCREMENT,
  FECHA DATETIME,
  DESCRIPCION VARCHAR(200),

  CONSTRAINT PK_IDLOG PRIMARY KEY(IDLOG)
);


DROP TABLE IF EXISTS LISTACOMPRA.HISTORICO;
CREATE TABLE LISTACOMPRA.HISTORICO (
  IDHISTORICO INT NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(200),
  CANTIDAD INT,

  CONSTRAINT PK_IDHISTORICO PRIMARY KEY(IDHISTORICO)
);

INSERT INTO LISTACOMPRA.HISTORICO (NOMBRE, CANTIDAD) VALUES ('Número de Listas Creadas:', 0);
INSERT INTO LISTACOMPRA.HISTORICO (NOMBRE, CANTIDAD) VALUES ('Número de Listas Activas:', 0);
INSERT INTO LISTACOMPRA.HISTORICO (NOMBRE, CANTIDAD) VALUES ('Número de Listas con Elementos pendientes de compra:', 0);

USE LISTACOMPRA;

CREATE OR REPLACE VIEW PRODUCTOSENLISTAS AS
  SELECT P.NOMBRE, SUM(L.CANTIDAD) AS CANTIDAD FROM PRODUCTOS AS P
  INNER JOIN LISTAPRODUCTOS AS L
  ON P.IDPRODUCTO = L.IDPRODUCTO
  GROUP BY P.IDPRODUCTO;
